document_map = [('info for survey takers', 'https://www.qualtrics.com/support/survey-platform/information-survey-takers/'),
                ('projects',
                 'https://www.qualtrics.com/support/survey-platform/my-projects/my-projects-overview/'),
                ('survey', 'https://www.qualtrics.com/support/survey-platform/survey-module/survey-module-overview/'),
                ('workflows', 'https://www.qualtrics.com/support/survey-platform/actions-module/setting-up-actions/'),
                ('workflows',
                 'https://www.qualtrics.com/support/survey-platform/actions-module/survey-response-events/'),
                ('workflows', 'https://www.qualtrics.com/support/survey-platform/actions-page/actions-in-global-navigation/'),
                ('ticket workflows', 'https://www.qualtrics.com/support/survey-platform/actions-module/ticket-events/'),
                ('workflows events',
                 'https://www.qualtrics.com/support/survey-platform/actions-page/survey-definition-events/'),
                ('workflow events', 'https://www.qualtrics.com/support/survey-platform/actions-page/servicenow-events/'),
                ('workflow events', 'https://www.qualtrics.com/support/survey-platform/actions-module/json-events/'),
                ('workflow events',
                 'https://www.qualtrics.com/support/survey-platform/actions-module/salesforce-workflow-rule-event/'),
                ('workflow events',
                 'https://www.qualtrics.com/support/survey-platform/actions-page/xm-directory-funnel-event/'),
                ('workflow events',
                 'https://www.qualtrics.com/support/survey-platform/actions-page/events/experience-id-segments-events/'),
                ('workflow events',
                 'https://www.qualtrics.com/support/survey-platform/actions-page/events/dataset-record-events/'),
                ('workflow events',
                 'https://www.qualtrics.com/support/survey-platform/actions-page/events/experience-id-change-event/'),
                ('workflow tasks', 'https://www.qualtrics.com/support/survey-platform/actions-module/ticketing/tickets-task/'),
                ('workflow tasks', 'https://www.qualtrics.com/support/survey-platform/actions-module/ticketing/update-ticket-task/'),
                ('workflow tasks', 'https://www.qualtrics.com/support/survey-platform/actions-module/email-task/'),
                ('workflow tasks',
                 'https://www.qualtrics.com/support/survey-platform/actions-module/xm-directory-task/'),
                ('workflow tasks',
                 'https://www.qualtrics.com/support/survey-platform/actions-module/notifications-feed-task/'),
                ('single instance incentives',
                 'https://www.qualtrics.com/support/survey-platform/actions-module/single-instance-incentives/'),
                ('workflow tasks', 'https://www.qualtrics.com/support/survey-platform/actions-module/code-task/'),
                ('qualtrics file service',
                 'https://www.qualtrics.com/support/survey-platform/actions-page/etl-workflows/data-extractor-tasks/extract-data-from-qualtrics-file-service-task/'),
                ('extract data from sftp files task',
                 'https://www.qualtrics.com/support/survey-platform/actions-page/extract-data-from-sftp-files-task/'),
                ('extract data from salesforce task',
                 'https://www.qualtrics.com/support/survey-platform/actions-page/etl-workflows/data-extractor-tasks/extract-data-from-salesforce-task/'),
                ('extract data from google drive task',
                 'https://www.qualtrics.com/support/survey-platform/actions-page/etl-workflows/data-extractor-tasks/extract-data-from-google-drive-task/'),
                ('import salesforce report data task',
                 'https://www.qualtrics.com/support/survey-platform/actions-page/etl-workflows/data-extractor-tasks/import-salesforce-report-data-task/'),
                ('extract response from a survey task',
                 'https://www.qualtrics.com/support/survey-platform/actions-page/etl-workflows/data-extractor-tasks/extract-responses-from-a-survey-task/'),
                ('load b2b account data into xm directory',
                 'https://www.qualtrics.com/support/survey-platform/actions-page/etl-workflows/data-loader-tasks/load-data-into-xm-directory-task/'),
                ('add contacts and transactions to xmd task',
                 'https://www.qualtrics.com/support/survey-platform/actions-page/etl-workflows/data-loader-tasks/add-contacts-and-transactions-to-xmd-task/'),
                ('load users into ex directory',
                 'https://www.qualtrics.com/support/survey-platform/actions-page/etl-workflows/data-loader-tasks/load-users-into-ex-directory-task/'),
                ('load users into cx directory',
                 'https://www.qualtrics.com/support/survey-platform/actions-page/etl-workflows/data-loader-tasks/load-users-into-cx-directory-task/'),
                ('load into a data project', 'https://www.qualtrics.com/support/survey-platform/actions-page/etl-workflows/data-loader-tasks/load-into-a-data-project-task/'),
                ('load into a data set task',
                 'https://www.qualtrics.com/support/survey-platform/actions-page/etl-workflows/data-loader-tasks/load-into-a-data-set-task/'),
                ('load data into sftp task', 'https://www.qualtrics.com/support/survey-platform/actions-page/etl-workflows/data-loader-tasks/load-data-into-sftp-task/'),
                ('text iq', 'https://www.qualtrics.com/support/survey-platform/data-and-analysis-module/text-iq/text-iq-functionality/'),
                ('text iq', 'https://www.qualtrics.com/support/survey-platform/data-and-analysis-module/text-iq/topics-in-text-iq/'),
                ('text iq', 'https://www.qualtrics.com/support/survey-platform/data-and-analysis-module/text-iq/sentiment-analysis/'),
                ('text iq', 'https://www.qualtrics.com/support/survey-platform/data-and-analysis-module/text-iq/widgets-in-text-iq/'),
                ('text iq',
                 'https://www.qualtrics.com/support/vocalize/dashboard-settings-cx/text-analysis-cx/'),
                ('website feedback project',
                 'https://www.qualtrics.com/support/website-app-feedback/creating-website-app-feedback-project/'),
                ('website creative', 'https://www.qualtrics.com/support/website-app-feedback/getting-started-with-website-app-feedback/step-3-building-your-creative/'),
                ('website intercept', 'https://www.qualtrics.com/support/website-app-feedback/getting-started-with-website-app-feedback/step-4-setting-up-your-intercept/'),
                ('website feedback project',
                 'https://www.qualtrics.com/support/website-app-feedback/getting-started-with-website-app-feedback/website-app-feedback-technical-documentation/'),
                ('xm directory', 'https://www.qualtrics.com/support/iq-directory/getting-started-iq-directory/getting-started-with-iq-directory/'),
                ('xm directory',
                 'https://www.qualtrics.com/support/iq-directory/getting-started-iq-directory/first-distribution-xm-directory/step-2-distributing-to-contacts-in-xm-directory/'),
                ('xm directory',
                 'https://www.qualtrics.com/support/iq-directory/getting-started-iq-directory/xm-directory-maintenance-organization-tips/'),
                ('qualtrics ids',
                 'https://www.qualtrics.com/support/integrations/api-integration/finding-qualtrics-ids/'),
                ('api', 'https://www.qualtrics.com/support/integrations/api-integration/using-qualtrics-api-documentation/'),
                ('website feedback project', 'https://www.qualtrics.com/support/website-app-feedback/getting-started-with-website-app-feedback/website-app-feedback-browser-cookies/'),
                ('website intercept', 'https://www.qualtrics.com/support/website-app-feedback/creatives-tab/creative-types/responsive-dialog-creative/'),
                ('website intercept', 'https://www.qualtrics.com/support/website-app-feedback/creatives-tab/creative-types/feedback-tab-creative/'),
                ('website intercept', 'https://www.qualtrics.com/support/website-app-feedback/intercepts-tab/edit-intercept-section/editing-intercepts/'),
                ('website intercept', 'https://www.qualtrics.com/support/website-app-feedback/intercepts-tab/edit-intercept-section/multiple-action-sets/'),
                ('website intercept', 'https://www.qualtrics.com/support/website-app-feedback/intercepts-tab/edit-intercept-section/action-set-logic/website-conditions/'),
                ('website intercept', 'https://www.qualtrics.com/support/website-app-feedback/intercepts-tab/edit-intercept-section/action-set-logic/user-info-conditions/'),
                ('website intercept', 'https://www.qualtrics.com/support/website-app-feedback/intercepts-tab/edit-intercept-section/action-set-logic/web-service-conditions/'),
                ('website intercept', 'https://www.qualtrics.com/support/website-app-feedback/intercepts-tab/activating-publishing-managing-intercepts/'),
                ('website creative', 'https://www.qualtrics.com/support/website-app-feedback/creatives-tab/edit-creative-section/'),
                ('website creative', 'https://www.qualtrics.com/support/website-app-feedback/creatives-tab/change-options-section-creatives/'),
                ('website creative', 'https://www.qualtrics.com/support/website-app-feedback/creatives-tab/publishing-managing-creatives/'),
                ('mobile creative', 'https://www.qualtrics.com/support/website-app-feedback/creatives-tab/creative-types/mobile-app-prompt-creative/'),
                ('mobile creative', 'https://www.qualtrics.com/support/website-app-feedback/creatives-tab/creative-types/mobile-notification-creative/'),
                ('website creative', 'https://www.qualtrics.com/support/website-app-feedback/creatives-tab/creative-types/responsive-dialog-creative/'),
                ('website creative', 'https://www.qualtrics.com/support/website-app-feedback/creatives-tab/creative-types/feedback-tab-creative/'),
                ('website creative', 'https://www.qualtrics.com/support/website-app-feedback/creatives-tab/creative-types/pop-over-creative/'),
                ('xm directory', 'https://www.qualtrics.com/support/iq-directory/fields-you-can-filter-by/'),
                ('xm directory', 'https://www.qualtrics.com/support/iq-directory/directory-contacts-tab/adding-directory-contacts/'),
                ('xm directory', 'https://www.qualtrics.com/support/iq-directory/directory-contacts-tab/managing-a-single-directory-contact/'),
                ('xm directory', 'https://www.qualtrics.com/support/iq-directory/directory-contacts-tab/directory-options/'),
                ('xm directory mailing lists',
                 'https://www.qualtrics.com/support/iq-directory/lists-tab/creating-mailing-lists/'),
                ('xm directory mailing lists',
                 'https://www.qualtrics.com/support/iq-directory/lists-tab/creating-mailing-list-samples/'),
                ('xm directory segments',
                 'https://www.qualtrics.com/support/iq-directory/segments-tab/'),
                ('xm directory mailing lists',
                 'https://www.qualtrics.com/support/iq-directory/lists-tab/managing-contacts-in-a-mailing-list/'),
                ('xm directory mailing lists',
                 'https://www.qualtrics.com/support/iq-directory/lists-tab/mailing-list-options/'),
                ('directory transactions',
                 'https://www.qualtrics.com/support/iq-directory/transactions-tab/transactions/'),
                ('distributions', 'https://www.qualtrics.com/support/iq-directory/distributions-tab-iq-directory/send-emails-in-iq-directory/'),
                ('distributions', 'https://www.qualtrics.com/support/iq-directory/distributions-tab-iq-directory/export-unique-links-in-iq-directory/'),
                ('distributions', 'https://www.qualtrics.com/support/iq-directory/distributions-tab-iq-directory/sms-distributions-in-xm-directory/'),
                ('website feedback projects', 'https://www.qualtrics.com/support/website-app-feedback/common-use-cases/xm-directory-contact-frequency-rules-for-digital-intercepts/'),
                ('directory automations',
                 'https://www.qualtrics.com/support/iq-directory/automations/contact-import-automation/'),
                ('directory automations',
                 'https://www.qualtrics.com/support/iq-directory/automations/file-import-sources-for-contact-automations/'),
                ('directory automations',
                 'https://www.qualtrics.com/support/iq-directory/automations/distribution-automation/'),
                ('directory automations',
                 'https://www.qualtrics.com/support/iq-directory/automations/managing-automations/'),
                ('directory automations',
                 'https://www.qualtrics.com/support/iq-directory/automations/automations-best-practices/'),
                ('pgp encryption', 'https://www.qualtrics.com/support/survey-platform/actions-module/pgp-encryption/'),
                ('library', 'https://www.qualtrics.com/support/survey-platform/account-library/library-overview/'),
                ('library', 'https://www.qualtrics.com/support/survey-platform/account-library/survey-library/'),
                ('library', 'https://www.qualtrics.com/support/survey-platform/survey-module/editing-questions/question-types-guide/pre-made-qualtrics-library-questions/'),
                ('library', 'https://www.qualtrics.com/support/survey-platform/account-library/graphics-library/'),
                ('library', 'https://www.qualtrics.com/support/survey-platform/account-library/files-library/'),
                ('library', 'https://www.qualtrics.com/support/survey-platform/account-library/message-library/'),
                ('ticketing', 'https://www.qualtrics.com/support/survey-platform/actions-module/ticketing/following-up-on-tickets/'),
                ('ticketing', 'https://www.qualtrics.com/support/survey-platform/actions-module/ticketing/ticketing-teams-roles/'),
                ('ticketing', 'https://www.qualtrics.com/support/survey-platform/actions-module/ticketing/follow-page-options/'),
                ('ticketing', 'https://www.qualtrics.com/support/survey-platform/actions-module/ticketing/ticket-settings/'),
                ('ticketing', 'https://www.qualtrics.com/support/survey-platform/actions-module/ticketing/ticket-permissions/'),
                ('ticketing', 'https://www.qualtrics.com/support/survey-platform/actions-module/ticketing/ticket-workflows/'),
                ('ticketing', 'https://www.qualtrics.com/support/survey-platform/actions-module/ticketing/ticket-reminders/'),
                ('ticketing', 'https://www.qualtrics.com/support/survey-platform/actions-module/ticketing/ticketing-queues/'),
                ('ticketing', 'https://www.qualtrics.com/support/survey-platform/actions-module/ticketing/ticket-reporting-datasets/'),
                ('ticketing', 'https://www.qualtrics.com/support/vocalize/common-use-cases-voc/closing-the-loop/'),
                ('dashboards', 'https://www.qualtrics.com/support/vocalize/getting-started-vocalize/dashboard-overview/'),
                ('dashboards', 'https://www.qualtrics.com/support/vocalize/getting-started-vocalize/pages-overview/'),
                ('dashboards', 'https://www.qualtrics.com/support/vocalize/getting-started-vocalize/mapping-data-for-widgets-cx/'),
                ('dashboards', 'https://www.qualtrics.com/support/vocalize/getting-started-vocalize/applying-dashboard-filters-cx/'),
                ('dashboards', 'https://www.qualtrics.com/support/vocalize/getting-started-vocalize/sharing-administering-dashboards/'),
                ('dashboards', 'https://www.qualtrics.com/support/vocalize/dashboard-settings-cx/dashboard-data/dashboard-data-overview/'),
                ('dashboards', 'https://www.qualtrics.com/support/vocalize/dashboard-settings-cx/dashboard-data/data-compatibility/'),
                ('dashboards', 'https://www.qualtrics.com/support/vocalize/dashboard-settings-cx/dashboard-data/recoding-values/'),
                ('dashboard textiq', 'https://www.qualtrics.com/support/vocalize/dashboard-settings-cx/text-analysis-cx/'),
                ('dashboards', 'https://www.qualtrics.com/support/vocalize/sharing-dashboards/sharing-your-dashboard/'),
                ('dashboard data restrictions',
                 'https://www.qualtrics.com/support/vocalize/sharing-dashboards/setting-data-restrictions/'),
                ('dashboard data export', 'https://www.qualtrics.com/support/vocalize/sharing-dashboards/exporting-data-from-vocalize/'), ('respondent funnel',
                                                                                                                                           'https://www.qualtrics.com/support/vocalize/widgets/xm-directory-respondent-funnel/'),
                ('linking qualtrics and salesforce',
                 'https://www.qualtrics.com/support/integrations/salesforce-integration/linking-qualtrics-and-salesforce/'),
                ('salesforce extension', 'https://www.qualtrics.com/support/integrations/salesforce-integration/salesforce-integration-overview/'),
                ('using salesforce to trigger surveys',
                 'https://www.qualtrics.com/support/integrations/salesforce-integration/triggering-and-emailing-surveys/'),
                ('salesforce response mapping',
                 'https://www.qualtrics.com/support/integrations/salesforce-integration/response-mapping/'),
                ('salesforce web to lead',
                 'https://www.qualtrics.com/support/integrations/salesforce-integration/web-to-lead/'),
                ('salesforce app', 'https://www.qualtrics.com/support/integrations/salesforce-integration/salesforce-app/salesforce-app-overview/'),
                ('salesforce distribution', 'https://www.qualtrics.com/support/integrations/salesforce-integration/more-salesforce-integration/other-salesforce-distribution-methods/'),
                ('salesforce extension', 'https://www.qualtrics.com/support/integrations/salesforce-integration/more-salesforce-integration/salesforce-best-practices/'),
                ('teableau extension',
                 'https://www.qualtrics.com/support/integrations/tableau-integration/'),
                ('marketo extension', 'https://www.qualtrics.com/support/integrations/marketo-integration/marketo-integration-overview/'),
                ('sending survey invites with marketo',
                 'https://www.qualtrics.com/support/integrations/marketo-integration/using-the-marketo-integration/'),
                ('marketo task', 'https://www.qualtrics.com/support/integrations/marketo-integration/custom-activities-in-marketo/'),
                ('adobe analytics', 'https://www.qualtrics.com/support/integrations/adobe-analytics-integration/'),
                ('adobe analytics',
                 'https://www.qualtrics.com/support/integrations/adobe-analytics-migration/'),
                ('api extension', 'https://www.qualtrics.com/support/integrations/api-integration/overview/'),
                ('microsoft dynamics', 'https://www.qualtrics.com/support/integrations/ms-dynamics/dynamics-response-mapping-web-to-lead/'),
                ('zendesk', 'https://www.qualtrics.com/support/survey-platform/actions-module/zendesk-events/'),
                ('zendesk', 'https://www.qualtrics.com/support/integrations/zendesk-integration/'),
                ('servicenow', 'https://www.qualtrics.com/support/survey-platform/actions-page/servicenow-events/'),
                ('servicenow', 'https://www.qualtrics.com/support/integrations/servicenow-integration/'),
                ('servicenow', 'https://www.qualtrics.com/support/iq-directory/directory-contacts-tab/embedding-xm-directory-profile-cards-in-servicenow/'),
                ('twilio', 'https://www.qualtrics.com/support/integrations/twilio-segment/twilio-segment-event/'),
                ('twilio', 'https://www.qualtrics.com/support/integrations/twilio-segment/twilio-segment-task/'),
                ('hubspot', 'https://www.qualtrics.com/support/integrations/hubspot-integration/'),
                ('zapier', 'https://www.qualtrics.com/support/integrations/zapier-integration/'),
                ('freshworks', 'https://www.qualtrics.com/support/integrations/freshworks-integration/'),
                ('jira', 'https://www.qualtrics.com/support/integrations/jira-integration/'),
                ('qualtrics developer portal', 'https://www.qualtrics.com/support/integrations/developer-portal/')]
